// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VTOP_integration.h for the primary calling header

#ifndef VERILATED_VTOP_INTEGRATION_CLUSTERGROUP_H_
#define VERILATED_VTOP_INTEGRATION_CLUSTERGROUP_H_  // guard

#include "verilated.h"
class VTOP_integration_Iact_SRAM_Bank;
class VTOP_integration_ProcessingElement;


class VTOP_integration__Syms;

class alignas(VL_CACHE_LINE_BYTES) VTOP_integration_ClusterGroup final : public VerilatedModule {
  public:
    // CELLS
    VTOP_integration_ProcessingElement* __PVT__PE_Cluster_inst__DOT__PE_INST_R__BRA__0__KET____DOT__PE_INST_C__BRA__0__KET____DOT__pe;
    VTOP_integration_ProcessingElement* __PVT__PE_Cluster_inst__DOT__PE_INST_R__BRA__0__KET____DOT__PE_INST_C__BRA__1__KET____DOT__pe;
    VTOP_integration_ProcessingElement* __PVT__PE_Cluster_inst__DOT__PE_INST_R__BRA__0__KET____DOT__PE_INST_C__BRA__2__KET____DOT__pe;
    VTOP_integration_ProcessingElement* __PVT__PE_Cluster_inst__DOT__PE_INST_R__BRA__1__KET____DOT__PE_INST_C__BRA__0__KET____DOT__pe;
    VTOP_integration_ProcessingElement* __PVT__PE_Cluster_inst__DOT__PE_INST_R__BRA__1__KET____DOT__PE_INST_C__BRA__1__KET____DOT__pe;
    VTOP_integration_ProcessingElement* __PVT__PE_Cluster_inst__DOT__PE_INST_R__BRA__1__KET____DOT__PE_INST_C__BRA__2__KET____DOT__pe;
    VTOP_integration_ProcessingElement* __PVT__PE_Cluster_inst__DOT__PE_INST_R__BRA__2__KET____DOT__PE_INST_C__BRA__0__KET____DOT__pe;
    VTOP_integration_ProcessingElement* __PVT__PE_Cluster_inst__DOT__PE_INST_R__BRA__2__KET____DOT__PE_INST_C__BRA__1__KET____DOT__pe;
    VTOP_integration_ProcessingElement* __PVT__PE_Cluster_inst__DOT__PE_INST_R__BRA__2__KET____DOT__PE_INST_C__BRA__2__KET____DOT__pe;
    VTOP_integration_Iact_SRAM_Bank* __PVT__GLB_Cluster_inst__DOT__IACT_BANK_R__BRA__0__KET____DOT__IACT_BANK__BRA__0__KET____DOT__u;
    VTOP_integration_Iact_SRAM_Bank* __PVT__GLB_Cluster_inst__DOT__IACT_BANK_R__BRA__0__KET____DOT__IACT_BANK__BRA__1__KET____DOT__u;
    VTOP_integration_Iact_SRAM_Bank* __PVT__GLB_Cluster_inst__DOT__IACT_BANK_R__BRA__0__KET____DOT__IACT_BANK__BRA__2__KET____DOT__u;
    VTOP_integration_Iact_SRAM_Bank* __PVT__GLB_Cluster_inst__DOT__IACT_BANK_R__BRA__1__KET____DOT__IACT_BANK__BRA__0__KET____DOT__u;
    VTOP_integration_Iact_SRAM_Bank* __PVT__GLB_Cluster_inst__DOT__IACT_BANK_R__BRA__1__KET____DOT__IACT_BANK__BRA__1__KET____DOT__u;
    VTOP_integration_Iact_SRAM_Bank* __PVT__GLB_Cluster_inst__DOT__IACT_BANK_R__BRA__1__KET____DOT__IACT_BANK__BRA__2__KET____DOT__u;
    VTOP_integration_Iact_SRAM_Bank* __PVT__GLB_Cluster_inst__DOT__IACT_BANK_R__BRA__2__KET____DOT__IACT_BANK__BRA__0__KET____DOT__u;
    VTOP_integration_Iact_SRAM_Bank* __PVT__GLB_Cluster_inst__DOT__IACT_BANK_R__BRA__2__KET____DOT__IACT_BANK__BRA__1__KET____DOT__u;
    VTOP_integration_Iact_SRAM_Bank* __PVT__GLB_Cluster_inst__DOT__IACT_BANK_R__BRA__2__KET____DOT__IACT_BANK__BRA__2__KET____DOT__u;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(PE_cluster_iact_data_in_sel,0,0);
        VL_IN8(PE_cluster_iact_data_out_sel,1,0);
        VL_IN8(PE_cluster_psum_data_in_sel,0,0);
        VL_IN8(router_cluster_iact_data_in_sel,1,0);
        VL_IN8(router_cluster_iact_data_out_sel,1,0);
        VL_IN8(router_cluster_weight_data_in_sel,0,0);
        VL_IN8(router_cluster_weight_data_out_sel,0,0);
        VL_IN8(router_cluster_psum_data_in_sel,0,0);
        VL_IN8(router_cluster_psum_data_out_sel,0,0);
        VL_IN8(read_psum_en,0,0);
        VL_OUT8(cal_fin,0,0);
        VL_IN8(cg_en,0,0);
        VL_OUT8(PE_weight_load_en,0,0);
        VL_OUT8(GLB_iact_load_en,0,0);
        VL_IN8(src_GLB_load_fin,0,0);
        VL_OUT8(all_cal_fin,0,0);
        VL_IN8(psum_acc_en,0,0);
        VL_IN8(psum_acc_fin,0,0);
        VL_IN8(GLB_psum_write_en,0,0);
        VL_IN8(psum_SRAM_Bank_0_read_out_en,0,0);
        VL_IN8(psum_SRAM_Bank_1_read_out_en,0,0);
        VL_IN8(psum_SRAM_Bank_2_read_out_en,0,0);
        VL_IN8(PSUM_DEPTH,4,0);
        VL_IN8(psum_spad_clear,0,0);
        VL_IN8(int4_former_weight_mode,0,0);
        VL_IN8(int4_later_weight_mode,0,0);
        VL_IN8(iact_write_fin_clear,0,0);
        VL_IN8(weight_write_fin_clear,0,0);
        VL_OUT8(GLB_psum_0_data_in_ready,0,0);
        VL_IN8(GLB_psum_0_data_in_valid,0,0);
        VL_IN8(GLB_psum_0_data_out_ready,0,0);
        VL_OUT8(GLB_psum_0_data_out_valid,0,0);
        VL_OUT8(GLB_psum_1_data_in_ready,0,0);
        VL_IN8(GLB_psum_1_data_in_valid,0,0);
        VL_IN8(GLB_psum_1_data_out_ready,0,0);
        VL_OUT8(GLB_psum_1_data_out_valid,0,0);
        VL_OUT8(GLB_psum_2_data_in_ready,0,0);
        VL_IN8(GLB_psum_2_data_in_valid,0,0);
        VL_IN8(GLB_psum_2_data_out_ready,0,0);
        VL_OUT8(GLB_psum_2_data_out_valid,0,0);
        VL_OUT8(router_iact_0_0_north_address_in_ready,0,0);
        VL_IN8(router_iact_0_0_north_address_in_valid,0,0);
        VL_IN8(router_iact_0_0_north_address_in,6,0);
        VL_OUT8(router_iact_0_0_north_data_in_ready,0,0);
        VL_IN8(router_iact_0_0_north_data_in_valid,0,0);
        VL_OUT8(router_iact_0_0_south_address_in_ready,0,0);
        VL_IN8(router_iact_0_0_south_address_in_valid,0,0);
        VL_IN8(router_iact_0_0_south_address_in,6,0);
        VL_OUT8(router_iact_0_0_south_data_in_ready,0,0);
        VL_IN8(router_iact_0_0_south_data_in_valid,0,0);
        VL_OUT8(router_iact_0_0_horiz_address_in_ready,0,0);
        VL_IN8(router_iact_0_0_horiz_address_in_valid,0,0);
        VL_IN8(router_iact_0_0_horiz_address_in,6,0);
        VL_OUT8(router_iact_0_0_horiz_data_in_ready,0,0);
        VL_IN8(router_iact_0_0_horiz_data_in_valid,0,0);
        VL_IN8(router_iact_0_0_north_address_out_ready,0,0);
        VL_OUT8(router_iact_0_0_north_address_out_valid,0,0);
        VL_OUT8(router_iact_0_0_north_address_out,6,0);
        VL_IN8(router_iact_0_0_north_data_out_ready,0,0);
        VL_OUT8(router_iact_0_0_north_data_out_valid,0,0);
        VL_IN8(router_iact_0_0_south_address_out_ready,0,0);
        VL_OUT8(router_iact_0_0_south_address_out_valid,0,0);
    };
    struct {
        VL_OUT8(router_iact_0_0_south_address_out,6,0);
        VL_IN8(router_iact_0_0_south_data_out_ready,0,0);
        VL_OUT8(router_iact_0_0_south_data_out_valid,0,0);
        VL_IN8(router_iact_0_0_horiz_address_out_ready,0,0);
        VL_OUT8(router_iact_0_0_horiz_address_out_valid,0,0);
        VL_OUT8(router_iact_0_0_horiz_address_out,6,0);
        VL_IN8(router_iact_0_0_horiz_data_out_ready,0,0);
        VL_OUT8(router_iact_0_0_horiz_data_out_valid,0,0);
        VL_OUT8(router_iact_0_1_north_address_in_ready,0,0);
        VL_IN8(router_iact_0_1_north_address_in_valid,0,0);
        VL_IN8(router_iact_0_1_north_address_in,6,0);
        VL_OUT8(router_iact_0_1_north_data_in_ready,0,0);
        VL_IN8(router_iact_0_1_north_data_in_valid,0,0);
        VL_OUT8(router_iact_0_1_south_address_in_ready,0,0);
        VL_IN8(router_iact_0_1_south_address_in_valid,0,0);
        VL_IN8(router_iact_0_1_south_address_in,6,0);
        VL_OUT8(router_iact_0_1_south_data_in_ready,0,0);
        VL_IN8(router_iact_0_1_south_data_in_valid,0,0);
        VL_OUT8(router_iact_0_1_horiz_address_in_ready,0,0);
        VL_IN8(router_iact_0_1_horiz_address_in_valid,0,0);
        VL_IN8(router_iact_0_1_horiz_address_in,6,0);
        VL_OUT8(router_iact_0_1_horiz_data_in_ready,0,0);
        VL_IN8(router_iact_0_1_horiz_data_in_valid,0,0);
        VL_IN8(router_iact_0_1_north_address_out_ready,0,0);
        VL_OUT8(router_iact_0_1_north_address_out_valid,0,0);
        VL_OUT8(router_iact_0_1_north_address_out,6,0);
        VL_IN8(router_iact_0_1_north_data_out_ready,0,0);
        VL_OUT8(router_iact_0_1_north_data_out_valid,0,0);
        VL_IN8(router_iact_0_1_south_address_out_ready,0,0);
        VL_OUT8(router_iact_0_1_south_address_out_valid,0,0);
        VL_OUT8(router_iact_0_1_south_address_out,6,0);
        VL_IN8(router_iact_0_1_south_data_out_ready,0,0);
        VL_OUT8(router_iact_0_1_south_data_out_valid,0,0);
        VL_IN8(router_iact_0_1_horiz_address_out_ready,0,0);
        VL_OUT8(router_iact_0_1_horiz_address_out_valid,0,0);
        VL_OUT8(router_iact_0_1_horiz_address_out,6,0);
        VL_IN8(router_iact_0_1_horiz_data_out_ready,0,0);
        VL_OUT8(router_iact_0_1_horiz_data_out_valid,0,0);
        VL_OUT8(router_iact_0_2_north_address_in_ready,0,0);
        VL_IN8(router_iact_0_2_north_address_in_valid,0,0);
        VL_IN8(router_iact_0_2_north_address_in,6,0);
        VL_OUT8(router_iact_0_2_north_data_in_ready,0,0);
        VL_IN8(router_iact_0_2_north_data_in_valid,0,0);
        VL_OUT8(router_iact_0_2_south_address_in_ready,0,0);
        VL_IN8(router_iact_0_2_south_address_in_valid,0,0);
        VL_IN8(router_iact_0_2_south_address_in,6,0);
        VL_OUT8(router_iact_0_2_south_data_in_ready,0,0);
        VL_IN8(router_iact_0_2_south_data_in_valid,0,0);
        VL_OUT8(router_iact_0_2_horiz_address_in_ready,0,0);
        VL_IN8(router_iact_0_2_horiz_address_in_valid,0,0);
        VL_IN8(router_iact_0_2_horiz_address_in,6,0);
        VL_OUT8(router_iact_0_2_horiz_data_in_ready,0,0);
        VL_IN8(router_iact_0_2_horiz_data_in_valid,0,0);
        VL_IN8(router_iact_0_2_north_address_out_ready,0,0);
        VL_OUT8(router_iact_0_2_north_address_out_valid,0,0);
        VL_OUT8(router_iact_0_2_north_address_out,6,0);
        VL_IN8(router_iact_0_2_north_data_out_ready,0,0);
        VL_OUT8(router_iact_0_2_north_data_out_valid,0,0);
        VL_IN8(router_iact_0_2_south_address_out_ready,0,0);
        VL_OUT8(router_iact_0_2_south_address_out_valid,0,0);
        VL_OUT8(router_iact_0_2_south_address_out,6,0);
        VL_IN8(router_iact_0_2_south_data_out_ready,0,0);
        VL_OUT8(router_iact_0_2_south_data_out_valid,0,0);
        VL_IN8(router_iact_0_2_horiz_address_out_ready,0,0);
    };
    struct {
        VL_OUT8(router_iact_0_2_horiz_address_out_valid,0,0);
        VL_OUT8(router_iact_0_2_horiz_address_out,6,0);
        VL_IN8(router_iact_0_2_horiz_data_out_ready,0,0);
        VL_OUT8(router_iact_0_2_horiz_data_out_valid,0,0);
        VL_OUT8(router_iact_1_0_north_address_in_ready,0,0);
        VL_IN8(router_iact_1_0_north_address_in_valid,0,0);
        VL_IN8(router_iact_1_0_north_address_in,6,0);
        VL_OUT8(router_iact_1_0_north_data_in_ready,0,0);
        VL_IN8(router_iact_1_0_north_data_in_valid,0,0);
        VL_OUT8(router_iact_1_0_south_address_in_ready,0,0);
        VL_IN8(router_iact_1_0_south_address_in_valid,0,0);
        VL_IN8(router_iact_1_0_south_address_in,6,0);
        VL_OUT8(router_iact_1_0_south_data_in_ready,0,0);
        VL_IN8(router_iact_1_0_south_data_in_valid,0,0);
        VL_OUT8(router_iact_1_0_horiz_address_in_ready,0,0);
        VL_IN8(router_iact_1_0_horiz_address_in_valid,0,0);
        VL_IN8(router_iact_1_0_horiz_address_in,6,0);
        VL_OUT8(router_iact_1_0_horiz_data_in_ready,0,0);
        VL_IN8(router_iact_1_0_horiz_data_in_valid,0,0);
        VL_IN8(router_iact_1_0_north_address_out_ready,0,0);
        VL_OUT8(router_iact_1_0_north_address_out_valid,0,0);
        VL_OUT8(router_iact_1_0_north_address_out,6,0);
        VL_IN8(router_iact_1_0_north_data_out_ready,0,0);
        VL_OUT8(router_iact_1_0_north_data_out_valid,0,0);
        VL_IN8(router_iact_1_0_south_address_out_ready,0,0);
        VL_OUT8(router_iact_1_0_south_address_out_valid,0,0);
        VL_OUT8(router_iact_1_0_south_address_out,6,0);
        VL_IN8(router_iact_1_0_south_data_out_ready,0,0);
        VL_OUT8(router_iact_1_0_south_data_out_valid,0,0);
        VL_IN8(router_iact_1_0_horiz_address_out_ready,0,0);
        VL_OUT8(router_iact_1_0_horiz_address_out_valid,0,0);
        VL_OUT8(router_iact_1_0_horiz_address_out,6,0);
        VL_IN8(router_iact_1_0_horiz_data_out_ready,0,0);
        VL_OUT8(router_iact_1_0_horiz_data_out_valid,0,0);
        VL_OUT8(router_iact_1_1_north_address_in_ready,0,0);
        VL_IN8(router_iact_1_1_north_address_in_valid,0,0);
        VL_IN8(router_iact_1_1_north_address_in,6,0);
        VL_OUT8(router_iact_1_1_north_data_in_ready,0,0);
        VL_IN8(router_iact_1_1_north_data_in_valid,0,0);
        VL_OUT8(router_iact_1_1_south_address_in_ready,0,0);
        VL_IN8(router_iact_1_1_south_address_in_valid,0,0);
        VL_IN8(router_iact_1_1_south_address_in,6,0);
        VL_OUT8(router_iact_1_1_south_data_in_ready,0,0);
        VL_IN8(router_iact_1_1_south_data_in_valid,0,0);
        VL_OUT8(router_iact_1_1_horiz_address_in_ready,0,0);
        VL_IN8(router_iact_1_1_horiz_address_in_valid,0,0);
        VL_IN8(router_iact_1_1_horiz_address_in,6,0);
        VL_OUT8(router_iact_1_1_horiz_data_in_ready,0,0);
        VL_IN8(router_iact_1_1_horiz_data_in_valid,0,0);
        VL_IN8(router_iact_1_1_north_address_out_ready,0,0);
        VL_OUT8(router_iact_1_1_north_address_out_valid,0,0);
        VL_OUT8(router_iact_1_1_north_address_out,6,0);
        VL_IN8(router_iact_1_1_north_data_out_ready,0,0);
        VL_OUT8(router_iact_1_1_north_data_out_valid,0,0);
        VL_IN8(router_iact_1_1_south_address_out_ready,0,0);
        VL_OUT8(router_iact_1_1_south_address_out_valid,0,0);
        VL_OUT8(router_iact_1_1_south_address_out,6,0);
        VL_IN8(router_iact_1_1_south_data_out_ready,0,0);
        VL_OUT8(router_iact_1_1_south_data_out_valid,0,0);
        VL_IN8(router_iact_1_1_horiz_address_out_ready,0,0);
        VL_OUT8(router_iact_1_1_horiz_address_out_valid,0,0);
        VL_OUT8(router_iact_1_1_horiz_address_out,6,0);
        VL_IN8(router_iact_1_1_horiz_data_out_ready,0,0);
        VL_OUT8(router_iact_1_1_horiz_data_out_valid,0,0);
    };
    struct {
        VL_OUT8(router_iact_1_2_north_address_in_ready,0,0);
        VL_IN8(router_iact_1_2_north_address_in_valid,0,0);
        VL_IN8(router_iact_1_2_north_address_in,6,0);
        VL_OUT8(router_iact_1_2_north_data_in_ready,0,0);
        VL_IN8(router_iact_1_2_north_data_in_valid,0,0);
        VL_OUT8(router_iact_1_2_south_address_in_ready,0,0);
        VL_IN8(router_iact_1_2_south_address_in_valid,0,0);
        VL_IN8(router_iact_1_2_south_address_in,6,0);
        VL_OUT8(router_iact_1_2_south_data_in_ready,0,0);
        VL_IN8(router_iact_1_2_south_data_in_valid,0,0);
        VL_OUT8(router_iact_1_2_horiz_address_in_ready,0,0);
        VL_IN8(router_iact_1_2_horiz_address_in_valid,0,0);
        VL_IN8(router_iact_1_2_horiz_address_in,6,0);
        VL_OUT8(router_iact_1_2_horiz_data_in_ready,0,0);
        VL_IN8(router_iact_1_2_horiz_data_in_valid,0,0);
        VL_IN8(router_iact_1_2_north_address_out_ready,0,0);
        VL_OUT8(router_iact_1_2_north_address_out_valid,0,0);
        VL_OUT8(router_iact_1_2_north_address_out,6,0);
        VL_IN8(router_iact_1_2_north_data_out_ready,0,0);
        VL_OUT8(router_iact_1_2_north_data_out_valid,0,0);
        VL_IN8(router_iact_1_2_south_address_out_ready,0,0);
        VL_OUT8(router_iact_1_2_south_address_out_valid,0,0);
        VL_OUT8(router_iact_1_2_south_address_out,6,0);
        VL_IN8(router_iact_1_2_south_data_out_ready,0,0);
        VL_OUT8(router_iact_1_2_south_data_out_valid,0,0);
        VL_IN8(router_iact_1_2_horiz_address_out_ready,0,0);
        VL_OUT8(router_iact_1_2_horiz_address_out_valid,0,0);
        VL_OUT8(router_iact_1_2_horiz_address_out,6,0);
        VL_IN8(router_iact_1_2_horiz_data_out_ready,0,0);
        VL_OUT8(router_iact_1_2_horiz_data_out_valid,0,0);
        VL_OUT8(router_iact_2_0_north_address_in_ready,0,0);
        VL_IN8(router_iact_2_0_north_address_in_valid,0,0);
        VL_IN8(router_iact_2_0_north_address_in,6,0);
        VL_OUT8(router_iact_2_0_north_data_in_ready,0,0);
        VL_IN8(router_iact_2_0_north_data_in_valid,0,0);
        VL_OUT8(router_iact_2_0_south_address_in_ready,0,0);
        VL_IN8(router_iact_2_0_south_address_in_valid,0,0);
        VL_IN8(router_iact_2_0_south_address_in,6,0);
        VL_OUT8(router_iact_2_0_south_data_in_ready,0,0);
        VL_IN8(router_iact_2_0_south_data_in_valid,0,0);
        VL_OUT8(router_iact_2_0_horiz_address_in_ready,0,0);
        VL_IN8(router_iact_2_0_horiz_address_in_valid,0,0);
        VL_IN8(router_iact_2_0_horiz_address_in,6,0);
        VL_OUT8(router_iact_2_0_horiz_data_in_ready,0,0);
        VL_IN8(router_iact_2_0_horiz_data_in_valid,0,0);
        VL_IN8(router_iact_2_0_north_address_out_ready,0,0);
        VL_OUT8(router_iact_2_0_north_address_out_valid,0,0);
        VL_OUT8(router_iact_2_0_north_address_out,6,0);
        VL_IN8(router_iact_2_0_north_data_out_ready,0,0);
        VL_OUT8(router_iact_2_0_north_data_out_valid,0,0);
        VL_IN8(router_iact_2_0_south_address_out_ready,0,0);
        VL_OUT8(router_iact_2_0_south_address_out_valid,0,0);
        VL_OUT8(router_iact_2_0_south_address_out,6,0);
        VL_IN8(router_iact_2_0_south_data_out_ready,0,0);
        VL_OUT8(router_iact_2_0_south_data_out_valid,0,0);
        VL_IN8(router_iact_2_0_horiz_address_out_ready,0,0);
        VL_OUT8(router_iact_2_0_horiz_address_out_valid,0,0);
        VL_OUT8(router_iact_2_0_horiz_address_out,6,0);
        VL_IN8(router_iact_2_0_horiz_data_out_ready,0,0);
        VL_OUT8(router_iact_2_0_horiz_data_out_valid,0,0);
        VL_OUT8(router_iact_2_1_north_address_in_ready,0,0);
        VL_IN8(router_iact_2_1_north_address_in_valid,0,0);
        VL_IN8(router_iact_2_1_north_address_in,6,0);
        VL_OUT8(router_iact_2_1_north_data_in_ready,0,0);
    };
    struct {
        VL_IN8(router_iact_2_1_north_data_in_valid,0,0);
        VL_OUT8(router_iact_2_1_south_address_in_ready,0,0);
        VL_IN8(router_iact_2_1_south_address_in_valid,0,0);
        VL_IN8(router_iact_2_1_south_address_in,6,0);
        VL_OUT8(router_iact_2_1_south_data_in_ready,0,0);
        VL_IN8(router_iact_2_1_south_data_in_valid,0,0);
        VL_OUT8(router_iact_2_1_horiz_address_in_ready,0,0);
        VL_IN8(router_iact_2_1_horiz_address_in_valid,0,0);
        VL_IN8(router_iact_2_1_horiz_address_in,6,0);
        VL_OUT8(router_iact_2_1_horiz_data_in_ready,0,0);
        VL_IN8(router_iact_2_1_horiz_data_in_valid,0,0);
        VL_IN8(router_iact_2_1_north_address_out_ready,0,0);
        VL_OUT8(router_iact_2_1_north_address_out_valid,0,0);
        VL_OUT8(router_iact_2_1_north_address_out,6,0);
        VL_IN8(router_iact_2_1_north_data_out_ready,0,0);
        VL_OUT8(router_iact_2_1_north_data_out_valid,0,0);
        VL_IN8(router_iact_2_1_south_address_out_ready,0,0);
        VL_OUT8(router_iact_2_1_south_address_out_valid,0,0);
        VL_OUT8(router_iact_2_1_south_address_out,6,0);
        VL_IN8(router_iact_2_1_south_data_out_ready,0,0);
        VL_OUT8(router_iact_2_1_south_data_out_valid,0,0);
        VL_IN8(router_iact_2_1_horiz_address_out_ready,0,0);
        VL_OUT8(router_iact_2_1_horiz_address_out_valid,0,0);
        VL_OUT8(router_iact_2_1_horiz_address_out,6,0);
        VL_IN8(router_iact_2_1_horiz_data_out_ready,0,0);
        VL_OUT8(router_iact_2_1_horiz_data_out_valid,0,0);
        VL_OUT8(router_iact_2_2_north_address_in_ready,0,0);
        VL_IN8(router_iact_2_2_north_address_in_valid,0,0);
        VL_IN8(router_iact_2_2_north_address_in,6,0);
        VL_OUT8(router_iact_2_2_north_data_in_ready,0,0);
        VL_IN8(router_iact_2_2_north_data_in_valid,0,0);
        VL_OUT8(router_iact_2_2_south_address_in_ready,0,0);
        VL_IN8(router_iact_2_2_south_address_in_valid,0,0);
        VL_IN8(router_iact_2_2_south_address_in,6,0);
        VL_OUT8(router_iact_2_2_south_data_in_ready,0,0);
        VL_IN8(router_iact_2_2_south_data_in_valid,0,0);
        VL_OUT8(router_iact_2_2_horiz_address_in_ready,0,0);
        VL_IN8(router_iact_2_2_horiz_address_in_valid,0,0);
        VL_IN8(router_iact_2_2_horiz_address_in,6,0);
        VL_OUT8(router_iact_2_2_horiz_data_in_ready,0,0);
        VL_IN8(router_iact_2_2_horiz_data_in_valid,0,0);
        VL_IN8(router_iact_2_2_north_address_out_ready,0,0);
        VL_OUT8(router_iact_2_2_north_address_out_valid,0,0);
        VL_OUT8(router_iact_2_2_north_address_out,6,0);
        VL_IN8(router_iact_2_2_north_data_out_ready,0,0);
        VL_OUT8(router_iact_2_2_north_data_out_valid,0,0);
        VL_IN8(router_iact_2_2_south_address_out_ready,0,0);
        VL_OUT8(router_iact_2_2_south_address_out_valid,0,0);
        VL_OUT8(router_iact_2_2_south_address_out,6,0);
        VL_IN8(router_iact_2_2_south_data_out_ready,0,0);
        VL_OUT8(router_iact_2_2_south_data_out_valid,0,0);
        VL_IN8(router_iact_2_2_horiz_address_out_ready,0,0);
        VL_OUT8(router_iact_2_2_horiz_address_out_valid,0,0);
        VL_OUT8(router_iact_2_2_horiz_address_out,6,0);
        VL_IN8(router_iact_2_2_horiz_data_out_ready,0,0);
        VL_OUT8(router_iact_2_2_horiz_data_out_valid,0,0);
        VL_OUT8(router_weight_0_horiz_address_in_ready,0,0);
        VL_IN8(router_weight_0_horiz_address_in_valid,0,0);
        VL_IN8(router_weight_0_horiz_address_in,7,0);
        VL_OUT8(router_weight_0_horiz_data_in_ready,0,0);
        VL_IN8(router_weight_0_horiz_data_in_valid,0,0);
        VL_IN8(router_weight_0_horiz_address_out_ready,0,0);
        VL_OUT8(router_weight_0_horiz_address_out_valid,0,0);
        VL_OUT8(router_weight_0_horiz_address_out,7,0);
    };
    struct {
        VL_IN8(router_weight_0_horiz_data_out_ready,0,0);
        VL_OUT8(router_weight_0_horiz_data_out_valid,0,0);
        VL_OUT8(router_weight_1_horiz_address_in_ready,0,0);
        VL_IN8(router_weight_1_horiz_address_in_valid,0,0);
        VL_IN8(router_weight_1_horiz_address_in,7,0);
        VL_OUT8(router_weight_1_horiz_data_in_ready,0,0);
        VL_IN8(router_weight_1_horiz_data_in_valid,0,0);
        VL_IN8(router_weight_1_horiz_address_out_ready,0,0);
        VL_OUT8(router_weight_1_horiz_address_out_valid,0,0);
        VL_OUT8(router_weight_1_horiz_address_out,7,0);
        VL_IN8(router_weight_1_horiz_data_out_ready,0,0);
        VL_OUT8(router_weight_1_horiz_data_out_valid,0,0);
        VL_OUT8(router_weight_2_horiz_address_in_ready,0,0);
        VL_IN8(router_weight_2_horiz_address_in_valid,0,0);
        VL_IN8(router_weight_2_horiz_address_in,7,0);
        VL_OUT8(router_weight_2_horiz_data_in_ready,0,0);
        VL_IN8(router_weight_2_horiz_data_in_valid,0,0);
        VL_IN8(router_weight_2_horiz_address_out_ready,0,0);
        VL_OUT8(router_weight_2_horiz_address_out_valid,0,0);
        VL_OUT8(router_weight_2_horiz_address_out,7,0);
        VL_IN8(router_weight_2_horiz_data_out_ready,0,0);
        VL_OUT8(router_weight_2_horiz_data_out_valid,0,0);
        VL_OUT8(router_psum_0_north_in_ready,0,0);
        VL_IN8(router_psum_0_north_in_valid,0,0);
        VL_IN8(router_psum_0_south_out_ready,0,0);
        VL_OUT8(router_psum_0_south_out_valid,0,0);
        VL_OUT8(router_psum_1_north_in_ready,0,0);
        VL_IN8(router_psum_1_north_in_valid,0,0);
        VL_IN8(router_psum_1_south_out_ready,0,0);
        VL_OUT8(router_psum_1_south_out_valid,0,0);
        VL_OUT8(router_psum_2_north_in_ready,0,0);
        VL_IN8(router_psum_2_north_in_valid,0,0);
        VL_IN8(router_psum_2_south_out_ready,0,0);
        VL_OUT8(router_psum_2_south_out_valid,0,0);
        VL_OUT8(cg_south_psum_0_in_ready,0,0);
        VL_IN8(cg_south_psum_0_in_valid,0,0);
        VL_OUT8(cg_south_psum_1_in_ready,0,0);
        VL_IN8(cg_south_psum_1_in_valid,0,0);
        VL_OUT8(cg_south_psum_2_in_ready,0,0);
        VL_IN8(cg_south_psum_2_in_valid,0,0);
        VL_IN8(cg_north_psum_0_out_ready,0,0);
        VL_OUT8(cg_north_psum_0_out_valid,0,0);
        VL_IN8(cg_north_psum_1_out_ready,0,0);
        VL_OUT8(cg_north_psum_1_out_valid,0,0);
        VL_IN8(cg_north_psum_2_out_ready,0,0);
        VL_OUT8(cg_north_psum_2_out_valid,0,0);
        CData/*0:0*/ __PVT__PECluster_all_write_fin;
        CData/*0:0*/ __PVT__PECluster_all_cal_fin;
        CData/*0:0*/ __PVT__cg_ctrl_GLB_psum_0_write_en;
        CData/*0:0*/ __PVT__cg_ctrl_GLB_psum_0_write_done;
        CData/*0:0*/ __PVT__cg_ctrl_GLB_psum_0_read_en;
        CData/*0:0*/ __PVT__cg_ctrl_GLB_psum_1_write_en;
        CData/*0:0*/ __PVT__cg_ctrl_GLB_psum_1_write_done;
        CData/*0:0*/ __PVT__cg_ctrl_GLB_psum_1_read_en;
        CData/*0:0*/ __PVT__cg_ctrl_GLB_psum_2_write_en;
        CData/*0:0*/ __PVT__cg_ctrl_GLB_psum_2_write_done;
        CData/*0:0*/ __PVT__cg_ctrl_GLB_psum_2_read_en;
        CData/*0:0*/ __PVT__all_cal_fin_reg;
        CData/*0:0*/ GLB_Cluster_inst__DOT____Vcellout__PSUM_BANK__BRA__0__KET____DOT__u__psum_data_out_valid;
        CData/*0:0*/ GLB_Cluster_inst__DOT____Vcellinp__PSUM_BANK__BRA__0__KET____DOT__u__psum_data_out_ready;
        CData/*0:0*/ GLB_Cluster_inst__DOT____Vcellout__PSUM_BANK__BRA__0__KET____DOT__u__psum_data_in_ready;
        CData/*0:0*/ GLB_Cluster_inst__DOT____Vcellout__PSUM_BANK__BRA__1__KET____DOT__u__psum_data_out_valid;
        CData/*0:0*/ GLB_Cluster_inst__DOT____Vcellinp__PSUM_BANK__BRA__1__KET____DOT__u__psum_data_out_ready;
        CData/*0:0*/ GLB_Cluster_inst__DOT____Vcellout__PSUM_BANK__BRA__1__KET____DOT__u__psum_data_in_ready;
    };
    struct {
        CData/*0:0*/ GLB_Cluster_inst__DOT____Vcellout__PSUM_BANK__BRA__2__KET____DOT__u__psum_data_out_valid;
        CData/*0:0*/ GLB_Cluster_inst__DOT____Vcellinp__PSUM_BANK__BRA__2__KET____DOT__u__psum_data_out_ready;
        CData/*0:0*/ GLB_Cluster_inst__DOT____Vcellout__PSUM_BANK__BRA__2__KET____DOT__u__psum_data_in_ready;
        CData/*4:0*/ __PVT__GLB_Cluster_inst__DOT__PSUM_BANK__BRA__0__KET____DOT__u__DOT__write_count;
        CData/*0:0*/ __PVT__GLB_Cluster_inst__DOT__PSUM_BANK__BRA__0__KET____DOT__u__DOT__write_shake;
        CData/*4:0*/ __PVT__GLB_Cluster_inst__DOT__PSUM_BANK__BRA__1__KET____DOT__u__DOT__write_count;
        CData/*0:0*/ __PVT__GLB_Cluster_inst__DOT__PSUM_BANK__BRA__1__KET____DOT__u__DOT__write_shake;
        CData/*4:0*/ __PVT__GLB_Cluster_inst__DOT__PSUM_BANK__BRA__2__KET____DOT__u__DOT__write_count;
        CData/*0:0*/ __PVT__GLB_Cluster_inst__DOT__PSUM_BANK__BRA__2__KET____DOT__u__DOT__write_shake;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_0_0_write_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_0_1_write_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_0_2_write_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_1_0_write_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_1_1_write_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_1_2_write_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_2_0_write_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_2_1_write_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_2_2_write_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_0_0_read_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_0_1_read_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_0_2_read_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_1_0_read_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_1_1_read_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_1_2_read_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_2_0_read_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_2_1_read_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_2_2_read_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_psum_0_write_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_psum_1_write_fin_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_psum_2_write_fin_reg;
        CData/*2:0*/ __PVT__Cluster_Group_Controller_inst__DOT__CG_state;
        CData/*2:0*/ __PVT__Cluster_Group_Controller_inst__DOT__next_CG_state;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_write_en_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__psum_load_en_reg;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_iact_all_write_fin;
        CData/*0:0*/ __PVT__Cluster_Group_Controller_inst__DOT__GLB_psum_all_load_fin;
        VL_IN16(router_iact_0_0_north_data_in,15,0);
        VL_IN16(router_iact_0_0_south_data_in,15,0);
        VL_IN16(router_iact_0_0_horiz_data_in,15,0);
        VL_OUT16(router_iact_0_0_north_data_out,15,0);
        VL_OUT16(router_iact_0_0_south_data_out,15,0);
        VL_OUT16(router_iact_0_0_horiz_data_out,15,0);
        VL_IN16(router_iact_0_1_north_data_in,15,0);
        VL_IN16(router_iact_0_1_south_data_in,15,0);
        VL_IN16(router_iact_0_1_horiz_data_in,15,0);
        VL_OUT16(router_iact_0_1_north_data_out,15,0);
        VL_OUT16(router_iact_0_1_south_data_out,15,0);
        VL_OUT16(router_iact_0_1_horiz_data_out,15,0);
        VL_IN16(router_iact_0_2_north_data_in,15,0);
        VL_IN16(router_iact_0_2_south_data_in,15,0);
        VL_IN16(router_iact_0_2_horiz_data_in,15,0);
        VL_OUT16(router_iact_0_2_north_data_out,15,0);
        VL_OUT16(router_iact_0_2_south_data_out,15,0);
        VL_OUT16(router_iact_0_2_horiz_data_out,15,0);
        VL_IN16(router_iact_1_0_north_data_in,15,0);
        VL_IN16(router_iact_1_0_south_data_in,15,0);
        VL_IN16(router_iact_1_0_horiz_data_in,15,0);
        VL_OUT16(router_iact_1_0_north_data_out,15,0);
        VL_OUT16(router_iact_1_0_south_data_out,15,0);
        VL_OUT16(router_iact_1_0_horiz_data_out,15,0);
        VL_IN16(router_iact_1_1_north_data_in,15,0);
        VL_IN16(router_iact_1_1_south_data_in,15,0);
        VL_IN16(router_iact_1_1_horiz_data_in,15,0);
        VL_OUT16(router_iact_1_1_north_data_out,15,0);
    };
    struct {
        VL_OUT16(router_iact_1_1_south_data_out,15,0);
        VL_OUT16(router_iact_1_1_horiz_data_out,15,0);
        VL_IN16(router_iact_1_2_north_data_in,15,0);
        VL_IN16(router_iact_1_2_south_data_in,15,0);
        VL_IN16(router_iact_1_2_horiz_data_in,15,0);
        VL_OUT16(router_iact_1_2_north_data_out,15,0);
        VL_OUT16(router_iact_1_2_south_data_out,15,0);
        VL_OUT16(router_iact_1_2_horiz_data_out,15,0);
        VL_IN16(router_iact_2_0_north_data_in,15,0);
        VL_IN16(router_iact_2_0_south_data_in,15,0);
        VL_IN16(router_iact_2_0_horiz_data_in,15,0);
        VL_OUT16(router_iact_2_0_north_data_out,15,0);
        VL_OUT16(router_iact_2_0_south_data_out,15,0);
        VL_OUT16(router_iact_2_0_horiz_data_out,15,0);
        VL_IN16(router_iact_2_1_north_data_in,15,0);
        VL_IN16(router_iact_2_1_south_data_in,15,0);
        VL_IN16(router_iact_2_1_horiz_data_in,15,0);
        VL_OUT16(router_iact_2_1_north_data_out,15,0);
        VL_OUT16(router_iact_2_1_south_data_out,15,0);
        VL_OUT16(router_iact_2_1_horiz_data_out,15,0);
        VL_IN16(router_iact_2_2_north_data_in,15,0);
        VL_IN16(router_iact_2_2_south_data_in,15,0);
        VL_IN16(router_iact_2_2_horiz_data_in,15,0);
        VL_OUT16(router_iact_2_2_north_data_out,15,0);
        VL_OUT16(router_iact_2_2_south_data_out,15,0);
        VL_OUT16(router_iact_2_2_horiz_data_out,15,0);
        VL_IN16(router_weight_0_horiz_data_in,12,0);
        VL_OUT16(router_weight_0_horiz_data_out,12,0);
        VL_IN16(router_weight_1_horiz_data_in,12,0);
        VL_OUT16(router_weight_1_horiz_data_out,12,0);
        VL_IN16(router_weight_2_horiz_data_in,12,0);
        VL_OUT16(router_weight_2_horiz_data_out,12,0);
        VL_IN(GLB_psum_0_data_in,20,0);
        VL_OUT(GLB_psum_0_data_out,20,0);
        VL_IN(GLB_psum_1_data_in,20,0);
        VL_OUT(GLB_psum_1_data_out,20,0);
        VL_IN(GLB_psum_2_data_in,20,0);
        VL_OUT(GLB_psum_2_data_out,20,0);
        VL_IN(router_psum_0_north_in,20,0);
        VL_OUT(router_psum_0_south_out,20,0);
        VL_IN(router_psum_1_north_in,20,0);
        VL_OUT(router_psum_1_south_out,20,0);
        VL_IN(router_psum_2_north_in,20,0);
        VL_OUT(router_psum_2_south_out,20,0);
        VL_IN(cg_south_psum_0_in,20,0);
        VL_IN(cg_south_psum_1_in,20,0);
        VL_IN(cg_south_psum_2_in,20,0);
        VL_OUT(cg_north_psum_0_out,20,0);
        VL_OUT(cg_north_psum_1_out,20,0);
        VL_OUT(cg_north_psum_2_out,20,0);
        IData/*20:0*/ __PVT__GLB_Cluster_inst__DOT__PSUM_BANK__BRA__0__KET____DOT__u__DOT__Psum_Data_SRAM_BRAM_inst__DOT__doutb;
        IData/*20:0*/ __PVT__GLB_Cluster_inst__DOT__PSUM_BANK__BRA__1__KET____DOT__u__DOT__Psum_Data_SRAM_BRAM_inst__DOT__doutb;
        IData/*20:0*/ __PVT__GLB_Cluster_inst__DOT__PSUM_BANK__BRA__2__KET____DOT__u__DOT__Psum_Data_SRAM_BRAM_inst__DOT__doutb;
        VL_IN8(PE_disable[3][3],0,0);
        VL_IN16(GLB_iact_read_addr[3][3],9,0);
        VL_IN16(GLB_psum_write_addr[3],9,0);
        VL_IN16(GLB_psum_read_addr[3],9,0);
        VL_OUT8(GLB_iact_address_in_ready[3][3],0,0);
        VL_IN8(GLB_iact_address_in_valid[3][3],0,0);
        VL_IN8(GLB_iact_address_in[3][3],6,0);
        VL_OUT8(GLB_iact_data_in_ready[3][3],0,0);
        VL_IN8(GLB_iact_data_in_valid[3][3],0,0);
        VL_IN16(GLB_iact_data_in[3][3],15,0);
        VL_OUT8(GLB_weight_address_in_ready[3],0,0);
    };
    struct {
        VL_IN8(GLB_weight_address_in_valid[3],0,0);
        VL_IN8(GLB_weight_address_in[3],7,0);
        VL_OUT8(GLB_weight_data_in_ready[3],0,0);
        VL_IN8(GLB_weight_data_in_valid[3],0,0);
        VL_IN16(GLB_weight_data_in[3],12,0);
        VlUnpacked<CData/*0:0*/, 3> __PVT__PECluster_iact_address_in_ready;
        VlUnpacked<CData/*0:0*/, 3> __PVT__PECluster_iact_data_in_ready;
        VlUnpacked<CData/*0:0*/, 3> __PVT__PECluster_psum_in_ready;
        VlUnpacked<CData/*0:0*/, 3> __PVT__PECluster_psum_out_valid;
        VlUnpacked<IData/*20:0*/, 3> __PVT__PECluster_psum_out;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PECluster_PE_disable;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__GLBCluster_iact_address_in_valid;
        VlUnpacked<VlUnpacked<CData/*6:0*/, 3>, 3> __PVT__GLBCluster_iact_address_in;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__GLBCluster_iact_data_in_valid;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 3>, 3> __PVT__GLBCluster_iact_data_in;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__GLBCluster_iact_write_en;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__GLBCluster_iact_write_done;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__GLBCluster_iact_read_en;
        VlUnpacked<VlUnpacked<SData/*9:0*/, 3>, 3> __PVT__GLBCluster_iact_read_addr;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__GLBCluster_iact_read_done;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_GLB_address_in_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_GLB_address_in_valid;
        VlUnpacked<VlUnpacked<CData/*6:0*/, 3>, 3> __PVT__iact_GLB_address_in_bits;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_GLB_data_in_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_GLB_data_in_valid;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 3>, 3> __PVT__iact_GLB_data_in_bits;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_north_address_in_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_north_data_in_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_south_address_in_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_south_data_in_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_horiz_address_in_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_horiz_data_in_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_PE_address_out_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_PE_address_out_valid;
        VlUnpacked<VlUnpacked<CData/*6:0*/, 3>, 3> __PVT__iact_PE_address_out_bits;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_PE_data_out_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_PE_data_out_valid;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 3>, 3> __PVT__iact_PE_data_out_bits;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_north_address_out_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_north_data_out_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_south_address_out_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_south_data_out_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_horiz_address_out_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__iact_horiz_data_out_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_psum_in_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_psum_in_valid;
        VlUnpacked<VlUnpacked<IData/*20:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_psum_in;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_psum_out_ready;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_psum_out_valid;
        VlUnpacked<VlUnpacked<IData/*20:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_psum_out;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_iact_addr_in_valid;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_iact_addr_in;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_iact_data_in_valid;
        VlUnpacked<VlUnpacked<SData/*12:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_iact_data_in;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_weight_addr_in_valid;
        VlUnpacked<VlUnpacked<CData/*6:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_weight_addr_in;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_weight_data_in_valid;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_weight_data_in;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_psum_enq_en;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_do_load_en;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_cal_fin;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_iact_write_fin_clear;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_weight_write_fin_clear;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_write_fin;
    };
    struct {
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_disable;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_cal_fin_reg;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __PVT__PE_Cluster_inst__DOT__pe_write_fin_reg;
        VlUnpacked<CData/*0:0*/, 3> __PVT__PE_Cluster_inst__DOT__psum_in_v_ext;
        VlUnpacked<IData/*20:0*/, 3> __PVT__PE_Cluster_inst__DOT__psum_in_d_ext;
        VlUnpacked<CData/*0:0*/, 3> __PVT__PE_Cluster_inst__DOT__psum_in_south_v;
        VlUnpacked<IData/*20:0*/, 3> __PVT__PE_Cluster_inst__DOT__psum_in_south_d;
        VlUnpacked<CData/*0:0*/, 3> __PVT__PE_Cluster_inst__DOT__psum_out_rdy_ext;
        VlUnpacked<IData/*20:0*/, 512> __PVT__GLB_Cluster_inst__DOT__PSUM_BANK__BRA__0__KET____DOT__u__DOT__Psum_Data_SRAM_BRAM_inst__DOT__u0__DOT__u__DOT__mem;
        VlUnpacked<IData/*20:0*/, 512> __PVT__GLB_Cluster_inst__DOT__PSUM_BANK__BRA__1__KET____DOT__u__DOT__Psum_Data_SRAM_BRAM_inst__DOT__u0__DOT__u__DOT__mem;
        VlUnpacked<IData/*20:0*/, 512> __PVT__GLB_Cluster_inst__DOT__PSUM_BANK__BRA__2__KET____DOT__u__DOT__Psum_Data_SRAM_BRAM_inst__DOT__u0__DOT__u__DOT__mem;
    };

    // INTERNAL VARIABLES
    VTOP_integration__Syms* const vlSymsp;

    // CONSTRUCTORS
    VTOP_integration_ClusterGroup(VTOP_integration__Syms* symsp, const char* v__name);
    ~VTOP_integration_ClusterGroup();
    VL_UNCOPYABLE(VTOP_integration_ClusterGroup);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
