// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VTOP_integration.h for the primary calling header

#ifndef VERILATED_VTOP_INTEGRATION___024ROOT_H_
#define VERILATED_VTOP_INTEGRATION___024ROOT_H_  // guard

#include "verilated.h"
class VTOP_integration_ClusterGroup;


class VTOP_integration__Syms;

class alignas(VL_CACHE_LINE_BYTES) VTOP_integration___024root final : public VerilatedModule {
  public:
    // CELLS
    VTOP_integration_ClusterGroup* __PVT__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_0_0;
    VTOP_integration_ClusterGroup* __PVT__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_0_1;
    VTOP_integration_ClusterGroup* __PVT__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_1_0;
    VTOP_integration_ClusterGroup* __PVT__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_1_1;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(int4_weight_mode,0,0);
        VL_IN8(ifmap_BRAM_wr_in,0,0);
        VL_IN8(ifmap_BRAM_dina_in,7,0);
        VL_OUT8(result,3,0);
        CData/*0:0*/ TOP_integration__DOT__system_enable_temp;
        CData/*0:0*/ TOP_integration__DOT__ifmap_write_done;
        CData/*0:0*/ TOP_integration__DOT__system_enable;
        CData/*7:0*/ TOP_integration__DOT__ifmap_BRAM_douta;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__iact_in_valid;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__weight_addr_in_valid;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__weight_data_in_valid;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__MEM_read_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__ROM_read_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__ROM_weight_data_flag;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__ROM_weight_addr_flag;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__im2col_convert_one_stream_done;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__csc_iact_data_in_ready;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__csc_iact_data_in_valid;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__csc_iact_data_in;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__csc_iact_one_vector_done;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__csc_weight_data_in_ready;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__csc_weight_data_in_valid;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__csc_weight_data_in;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ReLU_data_out;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__pool_data_in;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__pool_data_out_valid;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__psum_SRAM_out_acc_data_out_valid;
        CData/*3:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__softmax_data_out;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__softmax_data_out_valid;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_csc_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_conv_flag;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_fc_flag;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__int4_former_weight_mode_wire;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__int4_later_weight_mode_wire;
        CData/*2:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_layer_count;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_ReLU_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_psum_acc_fin;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_psum_SRAM_out_acc_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_0_GLB_psum_0_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_0_GLB_psum_1_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_0_GLB_psum_2_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_1_GLB_psum_0_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_1_GLB_psum_1_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_1_GLB_psum_2_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_1_0_GLB_psum_0_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_1_0_GLB_psum_1_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_1_0_GLB_psum_2_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_1_1_GLB_psum_0_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_1_1_GLB_psum_1_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_1_1_GLB_psum_2_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_0_src_GLB_load_fin;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_0_cg_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_0_psum_SRAM_Bank_0_read_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_0_psum_SRAM_Bank_1_read_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_0_psum_SRAM_Bank_2_read_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_0_psum_spad_clear;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_0_iact_write_fin_clear;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_0_weight_write_fin_clear;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_1_src_GLB_load_fin;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_1_psum_SRAM_Bank_0_read_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_1_psum_SRAM_Bank_1_read_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_1_psum_SRAM_Bank_2_read_out_en;
    };
    struct {
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_1_0_src_GLB_load_fin;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_1_0_psum_SRAM_Bank_0_read_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_1_1_src_GLB_load_fin;
        CData/*4:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CSC_encoder_iact_matrix_height;
        CData/*4:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CSC_encoder_weight_matrix_height;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_im2col_enable;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_psum_rearrange_write_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_pool_enable;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__weight_addr_end;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__weight_data_end;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__csc_addr_end;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__CG_0_0_psum_acc_en;
        CData/*2:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__im2col_converter__DOT__weight_row_counter;
        CData/*2:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__im2col_converter__DOT__ofmap_col_counter;
        CData/*2:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__im2col_converter__DOT__ofmap_row_counter;
        CData/*2:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__im2col_converter__DOT__ifmap_col_counter;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__im2col_converter__DOT__convert_one_vector_done_dly0;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__im2col_converter__DOT__convert_one_vector_done_dly1;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__im2col_converter__DOT__convert_one_vector_done_dly2;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__im2col_converter__DOT__ofmap_col_done;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__im2col_converter__DOT__weight_row_done;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__im2col_converter__DOT__ofmap_row_done;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__im2col_converter__DOT__ifmap_col_done;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__data_in_FIFO_data_in;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__data_in_FIFO_data_out_valid;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__data_in_FIFO_data_out;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__address_out_FIFO_data_in_valid;
        CData/*6:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__address_out_FIFO_data_in;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__data_out_FIFO_data_in_valid;
        CData/*3:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__csc_count;
        CData/*6:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__csc_address;
        CData/*4:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__column_counter;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__zero_col;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__one_vector_fin_reg;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__end_flag_reg;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__first_col_flag;
        CData/*4:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__zero_count;
        CData/*4:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__count;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__one_col_fin;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__out_data_valid;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Data_in_FIFO__DOT__maybe_full;
        CData/*1:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Data_in_FIFO__DOT__Buffer_write_addr;
        CData/*1:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Data_in_FIFO__DOT__Buffer_read_addr;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Data_in_FIFO__DOT__Buffer_write_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Data_in_FIFO__DOT__empty;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Data_in_FIFO__DOT__data_in_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Data_in_FIFO__DOT__data_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Address_out_FIFO__DOT__maybe_full;
        CData/*1:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Address_out_FIFO__DOT__Buffer_write_addr;
        CData/*1:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Address_out_FIFO__DOT__Buffer_read_addr;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Address_out_FIFO__DOT__Buffer_write_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Address_out_FIFO__DOT__empty;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Address_out_FIFO__DOT__data_in_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Address_out_FIFO__DOT__data_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Data_out_FIFO__DOT__maybe_full;
        CData/*1:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Data_out_FIFO__DOT__Buffer_write_addr;
        CData/*1:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Data_out_FIFO__DOT__Buffer_read_addr;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Data_out_FIFO__DOT__Buffer_write_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Data_out_FIFO__DOT__empty;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Data_out_FIFO__DOT__data_in_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Data_out_FIFO__DOT__data_out_en;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__data_in_FIFO_data_in;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__data_in_FIFO_data_out_valid;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__data_in_FIFO_data_out;
    };
    struct {
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__address_out_FIFO_data_in_valid;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__address_out_FIFO_data_in;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__data_out_FIFO_data_in_valid;
        CData/*4:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__csc_count;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__csc_address;
        CData/*4:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__column_counter;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__zero_col;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__one_vector_fin_reg;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__end_flag_reg;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__first_col_flag;
        CData/*4:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__zero_count;
        CData/*4:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__count;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__one_col_fin;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__out_data_valid;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Data_in_FIFO__DOT__maybe_full;
        CData/*1:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Data_in_FIFO__DOT__Buffer_write_addr;
        CData/*1:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Data_in_FIFO__DOT__Buffer_read_addr;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Data_in_FIFO__DOT__Buffer_write_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Data_in_FIFO__DOT__empty;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Data_in_FIFO__DOT__data_in_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Data_in_FIFO__DOT__data_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Address_out_FIFO__DOT__maybe_full;
        CData/*1:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Address_out_FIFO__DOT__Buffer_write_addr;
        CData/*1:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Address_out_FIFO__DOT__Buffer_read_addr;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Address_out_FIFO__DOT__Buffer_write_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Address_out_FIFO__DOT__empty;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Address_out_FIFO__DOT__data_in_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Address_out_FIFO__DOT__data_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Data_out_FIFO__DOT__maybe_full;
        CData/*1:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Data_out_FIFO__DOT__Buffer_write_addr;
        CData/*1:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Data_out_FIFO__DOT__Buffer_read_addr;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Data_out_FIFO__DOT__Buffer_write_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Data_out_FIFO__DOT__empty;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Data_out_FIFO__DOT__data_in_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Data_out_FIFO__DOT__data_out_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__psum_rearrange__DOT__Psum_Rearrange_BRAM_inst__DOT__wr;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__psum_rearrange__DOT__Psum_Rearrange_BRAM_inst__DOT__doutb;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__psum_rearrange__DOT__Psum_Rearrange_BRAM_inst__DOT__clear_flag;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__Streaming_Max_pooling__DOT__top_left;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__Streaming_Max_pooling__DOT__current_left;
        CData/*4:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__Streaming_Max_pooling__DOT__row_count;
        CData/*4:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__Streaming_Max_pooling__DOT__col_count;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__Streaming_Max_pooling__DOT__top_value;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__Streaming_Max_pooling__DOT__max_top;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__Streaming_Max_pooling__DOT__max_bottom;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__Streaming_Max_pooling__DOT__accept;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__Streaming_Max_pooling__DOT__end_of_row;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__Streaming_Max_pooling__DOT____Vlvbound_h9b7055a4__0;
        CData/*3:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__psum_SRAM_out_acc__DOT__idx;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__psum_SRAM_out_acc__DOT__en_reg;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__psum_SRAM_out_acc__DOT__en_pulse_reg;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__psum_SRAM_out_acc__DOT__data_in_en;
        CData/*3:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__softmax__DOT__data_idx;
        CData/*3:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__softmax__DOT__max_data_idx_temp;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__softmax__DOT__data_in_en;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__softmax__DOT__end_flag;
        CData/*5:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__state;
        CData/*5:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__next_state;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__LAYER0_LOAD_GLB_wire;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__LAYER1_LOAD_GLB_wire;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__LAYER0_CAL_wire;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__LAYER1_CAL_wire;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__LAYER2_CAL_wire;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__LAYER3_CAL_wire;
    };
    struct {
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__LAYER4_CAL_wire;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__LAYER0_PSUM_ACC_wire;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__LAYER1_PSUM_ACC_wire;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__LAYER0_READ_OUT_PSUM_wire;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__LAYER1_READ_OUT_PSUM_wire;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__LAYER2_READ_OUT_PSUM_wire;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__LAYER3_READ_OUT_PSUM_wire;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__LAYER4_READ_OUT_PSUM_wire;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__csc_en_reg;
        CData/*2:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__fc_weight_read_batch;
        CData/*5:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__GLB_iact_en_sel;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__ifmap_load_fin_reg;
        CData/*7:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__psum_acc_times;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__pool_row_count;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__pool_col_count;
        CData/*3:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__pool_ofmap_row_count;
        CData/*5:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__pool_cleanup_count;
        CData/*4:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__read_out_psum_count;
        CData/*4:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__read_out_psum_sel;
        CData/*4:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__read_out_psum_iter;
        CData/*4:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__read_out_psum_channel;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__first_iter_read_GLB_iact;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__second_iter_read_GLB_iact;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__third_iter_read_GLB_iact;
        CData/*1:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__layer_done_count;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__layer_iter_fin_reg;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__psum_acc_state_reg;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__pool_state_reg;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__im2col_convert_one_stream_done_reg;
        CData/*2:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__psum_read_out_channel;
        CData/*2:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__GLB_iact_load_batch;
        CData/*2:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__GLB_iact_load_channel;
        CData/*2:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__GLB_iact_load_iter;
        CData/*2:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__GLB_weight_load_channel;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__GLB_weight_load_end_reg;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__psum_read_out_oen_channel_read_done;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__read_out_psum_later_flag;
        CData/*4:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__fc_psum_rearrange_read_count;
        CData/*4:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__fc_psum_rearrange_read_channel;
        CData/*1:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__GLB_psum_read_channel;
        CData/*2:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__GLB_psum_read_batch;
        CData/*2:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__GLB_psum_read_sel;
        CData/*2:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__GLB_psum_read_sel_reg;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__LAYER2_READ_OUT_PSUM_reg;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__LAYER3_READ_OUT_PSUM_reg;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__LAYER4_READ_OUT_PSUM_reg;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__psum_SRAM_out_acc_en_dly0;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__psum_SRAM_out_acc_en_dly1;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__psum_SRAM_out_acc_en_dly2;
        CData/*3:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__fc_channel_acc_count;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__csc_en_fin;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__GLB_psum_read_channel_done;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__GLB_psum_read_batch_done;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__GLB_psum_read_sel_done;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__psum_acc_pulse;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__pool_pulse;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__layer_iter_fin_pulse;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__ifmap_load_fin;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__pool_fin;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__read_out_psum_iter_done;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__read_out_psum_channel_done;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__layer_iter_fin;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__layer_1_former_iter_fin;
        CData/*3:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__read_out_psum_sets;
    };
    struct {
        CData/*3:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__read_out_psum_iters;
        CData/*3:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__pool_ofmap_rows;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__load_PE_start;
        CData/*0:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__read_out_psum_former_fin;
        CData/*5:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__psum_depth;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clock__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        SData/*9:0*/ TOP_integration__DOT__ifmap_write_addr;
        SData/*9:0*/ TOP_integration__DOT__DRAM_read_addr;
        SData/*9:0*/ TOP_integration__DOT__ifmap_BRAM_addra;
        SData/*15:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__MEM_read_addr;
        SData/*15:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__ROM_data_out;
        SData/*15:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__ROM_read_addr;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__im2col_read_psum_addr;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_0_GLB_psum_0_write_addr;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_0_GLB_psum_1_write_addr;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_0_GLB_psum_2_write_addr;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_1_GLB_psum_0_write_addr;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_1_GLB_psum_1_write_addr;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_0_1_GLB_psum_2_write_addr;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_1_0_GLB_psum_0_write_addr;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_1_0_GLB_psum_1_write_addr;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_1_0_GLB_psum_2_write_addr;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_1_1_GLB_psum_0_write_addr;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_1_1_GLB_psum_1_write_addr;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_CG_1_1_GLB_psum_2_write_addr;
        SData/*11:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_psum_rearrange_write_addr;
        SData/*11:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ctrl_psum_rearrange_read_addr;
        SData/*11:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__data_out_FIFO_data_in;
        SData/*12:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__data_out_FIFO_data_in;
        SData/*11:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__psum_rearrange__DOT__Psum_Rearrange_BRAM_inst__DOT__addra;
        SData/*11:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__psum_rearrange__DOT__Psum_Rearrange_BRAM_inst__DOT__clear_count;
        SData/*11:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__psum_rearrange_read_addr_reg;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__CG_0_0_GLB_psum_0_read_addr_reg;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__CG_0_0_GLB_psum_1_read_addr_reg;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__CG_0_0_GLB_psum_2_read_addr_reg;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__CG_0_1_GLB_psum_0_read_addr_reg;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__CG_0_1_GLB_psum_1_read_addr_reg;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__CG_0_1_GLB_psum_2_read_addr_reg;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__CG_1_0_GLB_psum_0_read_addr_reg;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__CG_1_0_GLB_psum_1_read_addr_reg;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__CG_1_0_GLB_psum_2_read_addr_reg;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__CG_1_1_GLB_psum_0_read_addr_reg;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__CG_1_1_GLB_psum_1_read_addr_reg;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__CG_1_1_GLB_psum_2_read_addr_reg;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__GLB_iact_read_addr;
        SData/*9:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__read_out_psum_iter_next_base;
        IData/*20:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__psum_SRAM_out_acc_data_out;
        IData/*20:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__softmax_data_in;
        IData/*20:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__GLB_psum_out;
        IData/*20:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__psum_SRAM_out_acc__DOT____Vlvbound_hce32e949__0;
        IData/*20:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__softmax__DOT__max_data_temp;
        IData/*31:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__dbg_ifmap_load_cycles;
        IData/*31:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__dbg_glb_load_cycles;
        IData/*31:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__dbg_pe_load_cycles;
        IData/*31:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__dbg_conv_mac_cycles;
        IData/*31:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__dbg_fc1_mac_cycles;
        IData/*31:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__dbg_fc2_mac_cycles;
        IData/*31:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__dbg_fc3_mac_cycles;
        IData/*31:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__dbg_psum_acc_cycles;
    };
    struct {
        IData/*31:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__dbg_output_cycles;
        IData/*31:0*/ TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__TOP_controller__DOT__dbg_mem_read_cycles;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_0_PE_disable;
        VlUnpacked<VlUnpacked<SData/*9:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_0_GLB_iact_read_addr;
        VlUnpacked<SData/*9:0*/, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_0_GLB_psum_write_addr;
        VlUnpacked<SData/*9:0*/, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_0_GLB_psum_read_addr;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_0_GLB_iact_address_in_valid;
        VlUnpacked<VlUnpacked<CData/*6:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_0_GLB_iact_address_in;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_0_GLB_iact_data_in_valid;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_0_GLB_iact_data_in;
        VlUnpacked<CData/*0:0*/, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_0_GLB_weight_address_in_valid;
        VlUnpacked<CData/*7:0*/, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_0_GLB_weight_address_in;
        VlUnpacked<CData/*0:0*/, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_0_GLB_weight_data_in_valid;
        VlUnpacked<SData/*12:0*/, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_0_GLB_weight_data_in;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_1_PE_disable;
        VlUnpacked<VlUnpacked<SData/*9:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_1_GLB_iact_read_addr;
        VlUnpacked<SData/*9:0*/, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_1_GLB_psum_write_addr;
        VlUnpacked<SData/*9:0*/, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_1_GLB_psum_read_addr;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_1_GLB_iact_address_in_valid;
        VlUnpacked<VlUnpacked<CData/*6:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_1_GLB_iact_address_in;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_1_GLB_iact_data_in_valid;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_0_1_GLB_iact_data_in;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_0_PE_disable;
        VlUnpacked<VlUnpacked<SData/*9:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_0_GLB_iact_read_addr;
        VlUnpacked<SData/*9:0*/, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_0_GLB_psum_write_addr;
        VlUnpacked<SData/*9:0*/, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_0_GLB_psum_read_addr;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_0_GLB_iact_address_in_valid;
        VlUnpacked<VlUnpacked<CData/*6:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_0_GLB_iact_address_in;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_0_GLB_iact_data_in_valid;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_0_GLB_iact_data_in;
        VlUnpacked<CData/*0:0*/, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_0_GLB_weight_address_in_valid;
        VlUnpacked<CData/*7:0*/, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_0_GLB_weight_address_in;
        VlUnpacked<CData/*0:0*/, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_0_GLB_weight_data_in_valid;
        VlUnpacked<SData/*12:0*/, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_0_GLB_weight_data_in;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_1_PE_disable;
        VlUnpacked<VlUnpacked<SData/*9:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_1_GLB_iact_read_addr;
        VlUnpacked<SData/*9:0*/, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_1_GLB_psum_write_addr;
        VlUnpacked<SData/*9:0*/, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_1_GLB_psum_read_addr;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_1_GLB_iact_address_in_valid;
        VlUnpacked<VlUnpacked<CData/*6:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_1_GLB_iact_address_in;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_1_GLB_iact_data_in_valid;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 3>, 3> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CG_1_1_GLB_iact_data_in;
        VlUnpacked<CData/*7:0*/, 4> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Data_in_FIFO__DOT__Buffer;
        VlUnpacked<CData/*6:0*/, 4> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Address_out_FIFO__DOT__Buffer;
        VlUnpacked<SData/*11:0*/, 4> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_iact__DOT__Data_out_FIFO__DOT__Buffer;
        VlUnpacked<CData/*7:0*/, 4> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Data_in_FIFO__DOT__Buffer;
        VlUnpacked<CData/*7:0*/, 4> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Address_out_FIFO__DOT__Buffer;
        VlUnpacked<SData/*12:0*/, 4> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__CSC_Encoder_weight__DOT__Data_out_FIFO__DOT__Buffer;
        VlUnpacked<CData/*7:0*/, 4096> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__psum_rearrange__DOT__Psum_Rearrange_BRAM_inst__DOT__u0__DOT__u__DOT__mem;
        VlUnpacked<CData/*7:0*/, 24> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__Streaming_Max_pooling__DOT__line_buffer;
        VlUnpacked<IData/*20:0*/, 12> TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__psum_SRAM_out_acc__DOT__Buffer;
        VlUnpacked<SData/*15:0*/, 65536> TOP_integration__DOT__TOP_interface_inst__DOT__ROM_weight_inst__DOT__mem;
        VlUnpacked<CData/*7:0*/, 1024> TOP_integration__DOT__u0__DOT__u__DOT__mem;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_0_0____PVT__PE_Cluster_inst__DOT__pe_psum_in_valid__0;
        VlUnpacked<VlUnpacked<IData/*20:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_0_0____PVT__PE_Cluster_inst__DOT__pe_psum_in__0;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_0_0____PVT__PE_Cluster_inst__DOT__pe_psum_out_ready__0;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_0_1____PVT__PE_Cluster_inst__DOT__pe_psum_in_valid__0;
        VlUnpacked<VlUnpacked<IData/*20:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_0_1____PVT__PE_Cluster_inst__DOT__pe_psum_in__0;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_0_1____PVT__PE_Cluster_inst__DOT__pe_psum_out_ready__0;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_1_0____PVT__PE_Cluster_inst__DOT__pe_psum_in_valid__0;
        VlUnpacked<VlUnpacked<IData/*20:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_1_0____PVT__PE_Cluster_inst__DOT__pe_psum_in__0;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_1_0____PVT__PE_Cluster_inst__DOT__pe_psum_out_ready__0;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_1_1____PVT__PE_Cluster_inst__DOT__pe_psum_in_valid__0;
    };
    struct {
        VlUnpacked<VlUnpacked<IData/*20:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_1_1____PVT__PE_Cluster_inst__DOT__pe_psum_in__0;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_1_1____PVT__PE_Cluster_inst__DOT__pe_psum_out_ready__0;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_0_0____PVT__PE_Cluster_inst__DOT__pe_psum_in_valid__1;
        VlUnpacked<VlUnpacked<IData/*20:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_0_0____PVT__PE_Cluster_inst__DOT__pe_psum_in__1;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_0_0____PVT__PE_Cluster_inst__DOT__pe_psum_out_ready__1;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_0_1____PVT__PE_Cluster_inst__DOT__pe_psum_in_valid__1;
        VlUnpacked<VlUnpacked<IData/*20:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_0_1____PVT__PE_Cluster_inst__DOT__pe_psum_in__1;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_0_1____PVT__PE_Cluster_inst__DOT__pe_psum_out_ready__1;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_1_0____PVT__PE_Cluster_inst__DOT__pe_psum_in_valid__1;
        VlUnpacked<VlUnpacked<IData/*20:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_1_0____PVT__PE_Cluster_inst__DOT__pe_psum_in__1;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_1_0____PVT__PE_Cluster_inst__DOT__pe_psum_out_ready__1;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_1_1____PVT__PE_Cluster_inst__DOT__pe_psum_in_valid__1;
        VlUnpacked<VlUnpacked<IData/*20:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_1_1____PVT__PE_Cluster_inst__DOT__pe_psum_in__1;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 3> __Vtrigprevexpr___TOP__TOP_integration__DOT__TOP_interface_inst__DOT__TOP_inst__DOT__ClusterGroup_array__DOT__ClusterGroup_1_1____PVT__PE_Cluster_inst__DOT__pe_psum_out_ready__1;
    };
    VlTriggerVec<13> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<13> __VactTriggered;
    VlTriggerVec<13> __VnbaTriggered;

    // INTERNAL VARIABLES
    VTOP_integration__Syms* const vlSymsp;

    // CONSTRUCTORS
    VTOP_integration___024root(VTOP_integration__Syms* symsp, const char* v__name);
    ~VTOP_integration___024root();
    VL_UNCOPYABLE(VTOP_integration___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
